OAK-8902 | Listing lucene blobs using oak-run
oak-indexing/jackrabbit-oak pull request #23
Opened 2020-02-18 13:33 UTC by nit0906

2020-02-18 14:44 UTC, thomasmueller requested changes

2020-02-18 14:44 UTC, thomasmueller commented on oak-run/src/main/java/org/apache/jackrabbit/oak/run/DataStoreCheckCommand.java
>                      retrieveBlobReferences(blobStore, marker,
So, as far as I understand, for SegmentStore, it just traverses the nodes, but for all other stores (MongoDB / DocumentStore), it gets all the references of all the nodes... Right? That would be a lot of references... I think it should traverse just the nodes in verboseRootPath in both cases, if verboseRootPath is set.

2020-02-18 14:44 UTC, thomasmueller commented on oak-run/src/main/java/org/apache/jackrabbit/oak/run/DataStoreCheckCommand.java
> +                        nodeStore instanceof org.apache.jackrabbit.oak.segment.SegmentNodeStore)) ||
Ah I see, old and new segment store...

2020-02-18 14:50 UTC, thomasmueller commented on oak-run/src/main/java/org/apache/jackrabbit/oak/run/DataStoreCheckCommand.java
>                      retrieveBlobReferences(blobStore, marker,
Ah sorry, I see now! Looks good, I just didn't understand it.

2020-02-18 14:50 UTC, thomasmueller approved these changes

2020-02-20 09:57 UTC, fabriziofortino commented on oak-run/src/test/java/org/apache/jackrabbit/oak/run/DataStoreCommandTest.java
> +    public void testConsistencyVerboseRootPathNoMissing() throws Exception {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/gh/oak-indexing/jackrabbit-oak/pullRequest?prid=5026544)

2020-02-20 09:57 UTC, fabriziofortino commented on oak-run/src/test/java/org/apache/jackrabbit/oak/run/DataStoreCommandTest.java
> +    public void testConsistencyVerboseRootPath() throws Exception {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/gh/oak-indexing/jackrabbit-oak/pullRequest?prid=5026544)

2020-02-20 09:57 UTC, fabriziofortino commented on oak-run/src/test/java/org/apache/jackrabbit/oak/run/DataStoreCommandTest.java
> +    public void testConsistencyVerboseRootPathWithDeleted() throws Exception {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [JUnit tests should include assert() or fail()](https://app.codacy.com/gh/oak-indexing/jackrabbit-oak/pullRequest?prid=5026544)

2020-02-20 09:57 UTC, fabriziofortino commented on oak-run/src/test/java/org/apache/jackrabbit/oak/run/DataStoreCommandTest.java
> +        assertFalse(true);
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [assertTrue(true) or similar statements are unnecessary](https://app.codacy.com/gh/oak-indexing/jackrabbit-oak/pullRequest?prid=5026544)

2020-02-20 09:57 UTC, fabriziofortino commented on oak-run/src/main/java/org/apache/jackrabbit/oak/run/DataStoreOptions.java
> +                "Root path to output backend formatted ids/paths").availableUnless(collectGarbage).availableIf(verbose).withRequiredArg().withValuesSeparatedBy(DELIM).ofType(String.class);;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [An empty statement (semicolon) not part of a loop](https://app.codacy.com/gh/oak-indexing/jackrabbit-oak/pullRequest?prid=5026544)

2020-04-14 08:57 UTC, closed without merging